### PR TITLE
Fixed problem with big payload. At least bigger than 10MB. nuSoap is

### PR DESCRIPTION
**Pull request by perscheBo**
throwing "error in msg parsing: XML error parsing SOAP payload on line
3: No memory"
see: https://github.com/econea/nusoap/issues/48

### CODE REVIEW

**Comment by f3l1x** [comment]
Thanks. Could you please revert previous formatting? I can't see what really changed.

**Comment by perscheBo** [comment]
> Thanks. Could you please revert previous formatting? I can't see what really changed.

Yes. I hope this is correct now. :-)

**Comment by f3l1x** [comment]
Well, no diff at all. :-/ 

https://github.com/econea/nusoap/pull/49/files

**Comment by perscheBo** [comment]
Sorry, this commit contains the right diff.
https://github.com/econea/nusoap/pull/49/commits/b84080eed7c89c1303d1990d37610033fc12421c

**Comment by f3l1x** [comment]
Thanks.

**Pull request merged**
